version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - deploy_network
    container_name: backend
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
  redis:
    container_name: redis
    image: "redis/redis-stack:latest"
    ports:
      - 6379:6379
      - 8001:8001
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
     - deploy_network
networks:
  deploy_network:
    driver: bridge